import type { Metadata } from "next";
import { Header } from "./components/header";
import { Footer } from "./components/footer";

export const metadata: Metadata = {
  title: "Galeria",
  description: "Generated by create next app",
  keywords: ["", "", "", ""],
  openGraph: {
    title: "tattoo",
  },
  robots: {
    index: true,
    follow: true,
    noarchive: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
    }
  }
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div >
      <main className="bg-gradient-to-r from-zinc-950 via-zinc-900 to-zinc-950">
        <Header />
        {children}
        <Footer />
      </main>
    </div>
  );
}
