import type { Metadata } from "next";
import { Londrina_Solid, Inter } from "next/font/google";
import "./globals.css";
import { TextHero } from "@/components/textHero";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["200",],
});

const londrinna_solid = Londrina_Solid({
  variable: "--font-londrina-Solid",
  subsets: ["latin"],
  weight: ["400", "900",],
})

export const metadata: Metadata = {
  title: "STIG TATTOO",
  description: "Generated by create next app",
  keywords: ["", "", "", ""],
  openGraph: {
    title: "tattoo",
    images: [`${process.env.NEXT_PUBLIC_URL}/logo.jpg`]
  },
  robots: {
    index: true,
    follow: true,
    noarchive: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${londrinna_solid.variable} ${inter.variable} bg-gradient-to-r from-zinc-950 via-zinc-900 to-zinc-950`}>
        <TextHero />
        {children}
      </body>
    </html>
  );
}
